title: CIMAQ 
author: Birgit Ploetzeneder
description: > # this means to ignore newlines until "baseurl:"
  Additional library functions for the NI Vision Development Module / IMAQ
remote-theme: "mmistakes/minimal-mistakes"
